### ISSUE TITLE
Global Endpoints API raises 404 error

### ISSUE THREAD

**Issue by vsingh-msys** [go-chef/chef#176]
It seems that `Status`, `License` and `Users` APIs are not working properly it raises and 404 error.
eg:

```
res, err := client.Status.Get()
if err != nil {
	fmt.Print(err)
}
fmt.Print(res)

Output:
GET https://chef-server.test/organizations/_status: 404

```

Possible Fix:

Update the URL from relative to absolute at 
https://github.com/go-chef/chef/blob/5994b66a39a047fb4c56aada84d6c255ec64d81d/status.go#L18

Should be:
```
err = e.client.magicRequestDecoder("GET", "/_status", nil, &data) 
```

It applies to all the global endpoints APIs.

**Comment by MarkGibbons** [comment]
_status is a global end point.  Try using GET https://chef-server.test/_status

**Comment by vsingh-msys** [comment]
Hey @MarkGibbons thanks for the info. I just wanted to say the current implementation for getting the status `res, err := client.Status.Get()` not working as expected and it is raising 404.

**Comment by MarkGibbons** [comment]
The global endpoints don't accept the same format of base url as the the endpoints based on organizations.   Use https://chef-server.test/  for global end points instead of  https://chef-server.test/organizations/NAME/ for organization based end points.


For instance.
https://chefp01.nordstrom.net/_status works without authorization and returns.

{"status":"pong","upstreams":{"chef_elasticsearch":"pong","chef_sql":"pong","chef_index":"pong","oc_chef_authz":"pong","data_collector":"pong"},"keygen":{"keys":10,"max":10,"max_workers":2,"cur_max_workers":2,"inflight":0,"avail_workers":2,"start_size":0}}

**Comment by MarkGibbons** [comment]
Issue #41 is tracking the difference in use.

**Comment by vsingh-msys** [comment]
Thank you so much!!
