### ISSUE TITLE
Couldn't get list of nodes: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by bscott** [go-chef/chef#54]
Getting this error when invoking:

```
client.Nodes.List()
```

This link looks close to the issue: https://www.socketloop.com/tutorials/golang-invalid-character-looking-for-beginning-of-value

**Comment by spheromak** [comment]
closing this unless someone can give more info.

**Comment by sean-horn** [comment]
This happens when instead of hitting an organization endpoint on a server system that supports orgs, like https://chef.example.com/organizations/testorg, you hit the server root instead https://chef.example.com, which spews out HTML.

This can be fixed by adding a trailing slash to the BaseURL specification
