### ISSUE TITLE
Closing res.Body

### ISSUE THREAD

**Issue by meson10** [go-chef/chef#70]
From documentation
```
274	// Caller should close resp.Body when done reading from it.
```
Whereas the code here: https://github.com/go-chef/chef/blob/3abaf6b020a64924e7c891b70ca277e049e5f212/http.go#L220 doesn't close the response.

This leads to the host system Maxing out on Open File Descriptors if the ulimit is fairly low. In my case it was 256.

I can do a PR, but that would require a substantial amount of change, and If you guys don't have this on your priority list, I can take it up.

**Comment by spheromak** [comment]
The bug in `magicRequestDecoder()` was fixed in #72 (thanks for the pr). the `Do()` method returns pointer to a response, which as per stdlib the caller should be responsible for closing. `Do()` is provided for a user to craft up any wackiness they want to send at a chef-server. I don't expect it will ever close the response.
